repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files  # Prevents giant files from being committed
        args: ['--maxkb=2048']
      - id: check-yaml  # Checks yaml files for parseable syntax
      - id: check-toml  # Checks toml files for parseable syntax
      - id: check-merge-conflict  # Check for files containing merge conflict strings
      - id: check-case-conflict  # Check for files with names that would conflict on a case-insensitive filesystem
      - id: debug-statements  # Check for debugger imports and py37+ `breakpoint()` calls
      - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline
      - id: trailing-whitespace  # Trims trailing whitespace
      - id: mixed-line-ending  # Replaces or checks mixed line ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-ruff  # Runs ruff on Jupyter Notebooks
        args: ["--fix"]
      - id: nbqa-black  # Runs black on Jupyter Notebooks
      - id: nbqa-isort  # Runs isort on Jupyter Notebooks

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout  # Strips output from Jupyter notebooks

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests
          - types-setuptools
        args: [--ignore-missing-imports]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit  # Finds common security issues in Python code
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
