model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: null  # directory to save the model file
  filename: "epoch_{epoch:03d}"  # checkpoint filename
  monitor: "val_loss"  # name of the logged metric which determines when model is improving
  mode: "min"  # can be "max" or "min"
  save_top_k: 1  # save k best models (determined by above metric)
  save_last: true  # additionally always save model from last epoch
  verbose: false

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val_loss"  # name of the logged metric which determines when model is improving
  mode: "min"  # can be "max" or "min"
  patience: 3  # how many epochs of not improving until training stops
  min_delta: 0.0  # minimum change in the monitored metric to qualify as an improvement
  verbose: false

# image_logger:
#   _target_: diffusion_playground.callbacks.image_logger.ImageLoggerCallback
#   log_every_n_batches: 50  # Log images every 50 batches
#   num_samples: 8  # Number of images to log each time
