defaults:
  - paths_config
  - model: default_model
  - data: default_data_module
  - trainer: default_trainer
  - callbacks: default_callbacks
  - logger: wandb_logger
  - experiment: null
  - _self_

task_name: default
profiling: false
