site_name: Minecraft Voxel Flow Matching
site_description: A PyTorch Lightning template for Flow Matching models
site_author: Moust Holmes

repo_url: https://github.com/MoustHolmes/minecraft_voxel_flow

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - API Reference: api.md
  - Contributing: contributing.md
